spring:
  redis:
    host: 192.168.188.132
    password: 123456
    port: 6379
    database: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?serverTimezone=Asia/Shanghai&user=root&password=shiqi&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: shiqi
